version: '3.3'

services:

    # Trogdord
    trogdord:
        image: crankycyclops/trogdord:0.90.0
        volumes:
            - type: volume
              source: trogdord_dumped_games
              target: /usr/var/trogdord/state
              volume:
                nocopy: true

    # Web socket server (the glue between the PHP application and trogdord)
    sockserve:
        image: crankycyclops/trogserve-websocket:master
        volumes:
        volumes:
            - type: bind
              source: ./sockserve/config.env
              target: /sockserve/config.env
              read_only: true

    # TODO: I still need containers for the following services: PHP, Nginx, Redis, and MySQL

volumes:
    # trogdord will dump games here so that they can be restored later, even if the
    # container that dumped the game is destroyed
    trogdord_dumped_games:
