# To start, issue the following command:
# DOCKER_UID=xxx docker-compose up, where DOCKER_UID is the UID that owns the
# files bind-mounted into the php container.

version: '3.3'

services:

    # Trogdord and the web socket server will use redis to send and receive
    # messages to each other
    redis:
        image: redis:latest

    # Database for the PHP application
    database:
        image: mariadb:latest
        environment:
            MARIADB_RANDOM_ROOT_PASSWORD: 'yes'
            MARIADB_DATABASE: trogserve
            MARIADB_USER: trogserve
            MARIADB_PASSWORD: trogserve
        volumes:
            - type: volume
              source: trogserve_mysql
              target: /var/lib/mysql
              volume:
                nocopy: true

    # Php-fpm + trogdord extension
    php:
        image: crankycyclops/php8.1-fpm-trogdord-ext-npm:0.90.0
        user: "${DOCKER_UID}"
        depends_on:
            - "database"
        volumes:
            - ..:/var/www/trogserve
            - ./env:/var/www/trogserve/.env

    # Trogdord
    #
    # TODO: once I modify trogdord to allow includes from the root
    # trogdord.ini, I should then bind to a directory containing a
    # default container-specific configuration that can be modified
    # directly on the host.
    trogdord:
        image: crankycyclops/trogdord:0.90.0
        volumes:
            - ../games:/usr/share/trogdor
            - type: volume
              source: trogdord_dumped_games
              target: /usr/var/trogdord/state
              volume:
                nocopy: true

    # Web socket server (the glue between the PHP application and trogdord)
    sockserve:
        image: crankycyclops/trogserve-websocket:master
        depends_on:
            - "trogdord"
            - "redis"
        ports:
            - 9000:9000
        volumes:
            - type: bind
              source: ./sockserve/config.env
              target: /sockserve/config.env
              read_only: true

    # Web server for the frontned application
    nginx:
        image: nginx:stable
        depends_on:
            - "php"
        ports:
            - 8080:80
        volumes:
            - ../:/var/www/trogserve
            - ./nginx:/etc/nginx/conf.d

volumes:

    # Trogserve's database will persist here
    trogserve_mysql:

    # trogdord will dump games here so that they can be restored later, even if the
    # container that dumped the game is destroyed
    trogdord_dumped_games: